name: Docker Image Build and Deploy Images to GHCR CI

# 配置触发条件
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # Runs every 5 minutes.
  # Runs at 00:00 UTC every day.
  # Actions schedules run at most every 5 minutes.
  # schedule:
    # - cron: '*/5 * * * *'
    # - cron: '55 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 自定义环境变量，有风险危险调用，有什么私密变量请不要定义在这里
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - # 配置 QEMU 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - # 配置 buildx 用于多架构镜像的构建
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - # 打印 builder 支持信息
      name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - # 登录 docker 仓库
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - # 构建 amd64 镜像
      name: build amd64
      run: |
        docker buildx build --platform linux/amd64 -t ghcr.io/uilgnod-liamtoh/docker-arch-test:latest --push -f Dockerfile .
        
    - # 构建 arm64 镜像
      name: build arm64
      run: |
        docker buildx build --platform linux/arm64/v8 -t ghcr.io/uilgnod-liamtoh/docker-arch-test:latest --push -f Dockerfile .

    # 打印镜像信息
    - name: Inspect image
      run: |
        docker buildx imagetools inspect \
        ghcr.io/uilgnod-liamtoh/alpine-miniforge-jupyter:latest
